// Campaign: seven worlds, forty-two short stations. Each level teaches or tightens one idea.

function L(id, world, name, extra) {
  return {
    id,
    world,
    name,
    cols: 9,
    rows: 13,
    core: { x: 4, y: 6 },
    start: { minerals: 12, food: 8, crew: 3 },
    deposits: [],
    ice: [],
    blocked: [],
    wells: [],
    relics: [],
    prebuilt: [],
    allowed: ["corridor"],
    mechanics: {},
    waves: { first: 9999, interval: 48, count: 0, max: 0 },
    eatRate: 0,
    par: 90,
    hint: "",
    lesson: "",
    briefing: "",
    ...extra,
    start: { minerals: 12, food: 8, crew: 3, ...(extra.start || {}) },
    mechanics: { ...(extra.mechanics || {}) },
    waves: extra.waves || { first: 9999, interval: 48, count: 0, max: 0 },
  };
}

export const WORLDS = [
  { id: 1, name: "Quiet Dock", blurb: "Lay geometry. Tap rooms. Feed the white dashes." },
  { id: 2, name: "Supply Lines", blurb: "Food is a chain. Distance is a tax." },
  { id: 3, name: "Solar Weather", blurb: "The star bites anything a shield does not cover." },
  { id: 4, name: "Relic Shore", blurb: "Four mute monuments. The bag starts handing you shapes." },
  { id: 5, name: "Fold", blurb: "Gates make two tiles into one step." },
  { id: 6, name: "Ice Belt", blurb: "Frost holds kapsels. Heat writes a path." },
  { id: 7, name: "Ghost Current", blurb: "What you cannot see still eats geometry." },
];

export const LEVELS = [
  L("1-01", 1, "Spine", {
    lesson: "Rooms must kiss the station. Corridors are bone.",
    briefing: "The core is a plus of dark tiles. Place one corridor, then tap that blueprint. Assignment is the whole game; later halls send themselves.",
    hint: "Select Corridor, tap a tile touching the core, then tap the blueprint.",
    start: { minerals: 8, food: 0, crew: 3 },
    allowed: ["corridor"],
    mechanics: { teachAssign: true },
    win: { corridors: 3 },
    par: 50,
  }),
  L("1-02", 1, "Garden Duty", {
    lesson: "A garden grows meals. Tap it to send a kapsel.",
    briefing: "Place a garden, assign a kapsel, and let them carry pale food back to the core pantry. Assignment is not optional here either.",
    hint: "After it is built, tap the garden — not the kapsel.",
    start: { minerals: 8, food: 0, crew: 3 },
    allowed: ["corridor", "garden"],
    mechanics: { teachStaff: true },
    win: { rooms: { garden: 1 }, food: 4 },
    par: 70,
  }),
  L("1-03", 1, "The Vein", {
    lesson: "Extractors only bite pink mineral fields.",
    briefing: "A deposit glitters west of the core. Seat an extractor against it and bank six minerals in the pantry.",
    hint: "The L-piece must touch a pink field.",
    start: { minerals: 8, food: 4, crew: 3 },
    deposits: [{ x: 1, y: 6 }],
    allowed: ["corridor", "extractor"],
    win: { rooms: { extractor: 1 }, mineral: 8 },
    par: 80,
  }),
  L("1-04", 1, "Watchpost", {
    lesson: "Weapons are mute until a kapsel stands in them.",
    briefing: "Something sharp is coming from the dark. Build a gun, tap it, and keep the core intact.",
    hint: "Assign before the rim turns red.",
    start: { minerals: 12, food: 6, crew: 3 },
    allowed: ["corridor", "weapons"],
    waves: { first: 18, interval: 40, count: 2, hp: 28, speed: 22, max: 1 },
    win: { rooms: { weapons: 1 }, surviveWaves: 1 },
    par: 55,
  }),
  L("1-05", 1, "Berths", {
    lesson: "Quarters eat pantry meals and mint new kapsels.",
    briefing: "Grow the crew to five. Three meals, a little waiting, a new white dash.",
    hint: "Tap quarters. They will fetch food themselves.",
    start: { minerals: 12, food: 12, crew: 3 },
    allowed: ["corridor", "quarters"],
    win: { rooms: { quarters: 1 }, crew: 5 },
    par: 70,
  }),
  L("1-06", 1, "Station Hands", {
    lesson: "A living station feeds, mines, and shoots.",
    briefing: "You have the whole quiet kit. Hold two waves. Do not let the pantry go dark.",
    hint: "Two guns on opposite sides beat one fancy spine.",
    start: { minerals: 16, food: 10, crew: 4 },
    deposits: [{ x: 1, y: 6 }, { x: 7, y: 6 }],
    allowed: ["corridor", "garden", "extractor", "weapons", "quarters"],
    eatRate: 0.018,
    waves: { first: 24, interval: 28, count: (n) => 1 + n, hp: (n) => 24 + n * 10, max: 2 },
    win: { surviveWaves: 2, food: 1 },
    par: 90,
  }),

  L("2-01", 2, "Sludge", {
    lesson: "Gardens now grow biomass. Kitchens cook it into meals.",
    briefing: "The old direct harvest is gone. Staff a garden and a kitchen or the pantry stays empty.",
    hint: "Tap both rooms. Food is yellow; sludge is green.",
    start: { minerals: 16, food: 6, crew: 4 },
    mechanics: { kitchenChain: true },
    allowed: ["corridor", "garden", "kitchen"],
    eatRate: 0.01,
    win: { rooms: { kitchen: 1, garden: 1 }, food: 6 },
    par: 85,
  }),
  L("2-02", 2, "Long Haul", {
    lesson: "Every empty tile is a tax on time.",
    briefing: "The only deposit sits far south. Corridor there, extract, and still cook enough to keep four kapsels alive.",
    hint: "Build the road first. Production without a path is sculpture.",
    start: { minerals: 18, food: 8, crew: 4 },
    core: { x: 4, y: 3 },
    deposits: [{ x: 4, y: 10 }],
    mechanics: { kitchenChain: true },
    allowed: ["corridor", "garden", "extractor", "kitchen"],
    eatRate: 0.012,
    win: { mineral: 20, food: 10, rooms: { extractor: 1, kitchen: 1 } },
    par: 110,
  }),
  L("2-03", 2, "Two Kitchens", {
    lesson: "Two cooks are not twice as fast if sludge is scarce.",
    briefing: "Reach eight pantry meals. A second kitchen is optional; a second garden is usually not.",
    start: { minerals: 18, food: 4, crew: 4 },
    mechanics: { kitchenChain: true },
    allowed: ["corridor", "garden", "kitchen", "quarters"],
    eatRate: 0.016,
    win: { food: 8, crew: 4 },
    par: 90,
  }),
  L("2-04", 2, "Narrow Dock", {
    lesson: "The void has already claimed tiles. Thread the station through.",
    briefing: "Asteroids block the obvious spine. Survive one wave after you have a gun.",
    start: { minerals: 16, food: 8, crew: 4 },
    blocked: [
      { x: 4, y: 4 },
      { x: 4, y: 8 },
      { x: 2, y: 6 },
      { x: 6, y: 6 },
    ],
    deposits: [{ x: 0, y: 9 }],
    mechanics: { kitchenChain: true },
    allowed: ["corridor", "garden", "extractor", "kitchen", "weapons"],
    waves: { first: 32, interval: 30, count: 3, hp: 32, max: 1 },
    eatRate: 0.016,
    win: { rooms: { weapons: 1 }, surviveWaves: 1 },
    par: 95,
  }),
  L("2-05", 2, "Hungry Shift", {
    lesson: "Crew is a furnace. Too many mouths before the kitchen sings.",
    briefing: "You start with six kapsels and a thinning pantry. Stabilize food, then grow once more.",
    start: { minerals: 16, food: 12, crew: 6 },
    mechanics: { kitchenChain: true },
    allowed: ["corridor", "garden", "kitchen", "quarters"],
    eatRate: 0.022,
    win: { food: 8, crew: 7 },
    par: 100,
  }),
  L("2-06", 2, "Convoy", {
    lesson: "Hold the line while the chain still moves.",
    briefing: "Three waves. Keep a kitchen hot and at least two weapons staffed when the rim reddens.",
    start: { minerals: 20, food: 10, crew: 5 },
    deposits: [{ x: 1, y: 3 }, { x: 7, y: 10 }],
    mechanics: { kitchenChain: true },
    allowed: ["corridor", "garden", "extractor", "kitchen", "weapons", "quarters"],
    waves: { first: 22, interval: 24, count: (n) => 1 + n, hp: (n) => 26 + n * 12, max: 3 },
    eatRate: 0.022,
    win: { surviveWaves: 3, food: 1 },
    par: 120,
  }),

  L("3-01", 3, "First Flare", {
    lesson: "Unshielded rooms scorch when the star inhales.",
    briefing: "A flare is already on the clock. Raise a shield so the garden does not become pottery.",
    hint: "Shields protect a small radius. They do not need a kapsel.",
    start: { minerals: 16, food: 8, crew: 4 },
    mechanics: { flares: { first: 16, interval: 18, damage: 14, telegraph: 3 } },
    allowed: ["corridor", "garden", "shield"],
    win: { rooms: { shield: 1, garden: 1 }, food: 3 },
    par: 70,
  }),
  L("3-02", 3, "Umbrella", {
    lesson: "One shield cannot cover a sprawling station.",
    briefing: "Keep both a garden and an extractor alive through two flares, then bank food.",
    start: { minerals: 18, food: 6, crew: 4 },
    deposits: [{ x: 1, y: 9 }],
    mechanics: { flares: { first: 12, interval: 14, damage: 16, telegraph: 2.6 } },
    allowed: ["corridor", "garden", "extractor", "shield"],
    win: { rooms: { shield: 1, extractor: 1 }, food: 4 },
    par: 90,
  }),
  L("3-03", 3, "Exposed Vein", {
    lesson: "Sometimes the deposit sits outside the umbrella on purpose.",
    briefing: "Mine the far field. Stretch a second shield or finish before the extractor dies.",
    start: { minerals: 18, food: 8, crew: 4 },
    deposits: [{ x: 1, y: 3 }],
    mechanics: { flares: { first: 14, interval: 16, damage: 9, telegraph: 2.4 } },
    allowed: ["corridor", "extractor", "shield", "garden"],
    win: { mineral: 10, rooms: { extractor: 1 } },
    par: 85,
  }),
  L("3-04", 3, "Double Pulse", {
    lesson: "Flares and scouts share a calendar.",
    briefing: "Survive two waves while the star keeps biting. Guns on the rim, shield on the pantry.",
    start: { minerals: 20, food: 10, crew: 5 },
    deposits: [{ x: 7, y: 2 }],
    mechanics: { flares: { first: 14, interval: 16, damage: 12, telegraph: 2.5 } },
    allowed: ["corridor", "garden", "extractor", "weapons", "shield", "quarters"],
    waves: { first: 20, interval: 26, count: (n) => 2, hp: (n) => 30 + n * 8, max: 2 },
    eatRate: 0.018,
    win: { surviveWaves: 2, rooms: { shield: 1 } },
    par: 110,
  }),
  L("3-05", 3, "Glass House", {
    lesson: "A garden far from the shield is a dare.",
    briefing: "Produce eight meals with a station that wants to sprawl. The star will punish sprawl.",
    start: { minerals: 18, food: 8, crew: 4 },
    mechanics: { kitchenChain: true, flares: { first: 11, interval: 13, damage: 15, telegraph: 2.2 } },
    allowed: ["corridor", "garden", "kitchen", "shield"],
    eatRate: 0.02,
    win: { food: 8, rooms: { shield: 1 } },
    par: 100,
  }),
  L("3-06", 3, "Storm Season", {
    lesson: "Weather plus war. Compact geometry wins.",
    briefing: "Three waves, regular flares. If the core is bare, it will unstitch.",
    start: { minerals: 22, food: 12, crew: 5 },
    deposits: [{ x: 1, y: 6 }, { x: 8, y: 11 }],
    mechanics: { kitchenChain: true, flares: { first: 12, interval: 14, damage: 13, telegraph: 2.4 } },
    allowed: ["corridor", "garden", "extractor", "kitchen", "weapons", "quarters", "shield"],
    waves: { first: 18, interval: 22, count: (n) => 1 + n, hp: (n) => 28 + n * 12, max: 3 },
    eatRate: 0.02,
    win: { surviveWaves: 3 },
    par: 130,
  }),

  L("4-01", 4, "First Relic", {
    lesson: "A relic counts when built floor can walk to it.",
    briefing: "The pale obelisk east of the core is mute until a corridor touches it.",
    hint: "You do not build on the relic. You kiss it.",
    start: { minerals: 8, food: 6, crew: 3 },
    relics: [{ x: 8, y: 6 }],
    allowed: ["corridor"],
    win: { relics: 1 },
    par: 40,
  }),
  L("4-02", 4, "Opposite Shore", {
    lesson: "Two relics, two directions. Do not spend the whole bank on one road.",
    briefing: "North and south monuments. Link both.",
    start: { minerals: 12, food: 6, crew: 3 },
    relics: [{ x: 4, y: 0 }, { x: 4, y: 12 }],
    allowed: ["corridor"],
    win: { relics: 2 },
    par: 55,
  }),
  L("4-03", 4, "Guarded Archive", {
    lesson: "Scouts smell new floor.",
    briefing: "Link two relics and hold one wave. A gun on the new road is not vanity.",
    start: { minerals: 16, food: 8, crew: 4 },
    relics: [{ x: 0, y: 2 }, { x: 8, y: 10 }],
    allowed: ["corridor", "weapons", "garden"],
    waves: { first: 28, interval: 30, count: 3, hp: 34, max: 1 },
    win: { relics: 2, surviveWaves: 1 },
    par: 90,
  }),
  L("4-04", 4, "Four Corners", {
    lesson: "The bag hands you a shape. You still choose the room's job.",
    briefing: "Four relics. Each placement is a random tetromino. A plus of corridors is honest. A messy scribble still counts.",
    hint: "Rotate the bag piece. Kiss every monument.",
    start: { minerals: 28, food: 8, crew: 4 },
    relics: [
      { x: 0, y: 0 },
      { x: 8, y: 0 },
      { x: 0, y: 12 },
      { x: 8, y: 12 },
    ],
    allowed: ["corridor", "garden", "extractor", "weapons"],
    deposits: [{ x: 2, y: 6 }],
    mechanics: { pieceQueue: true },
    waves: { first: 48, interval: 28, count: 2, hp: 30, max: 1 },
    win: { relics: 4 },
    par: 120,
  }),
  L("4-05", 4, "Living Archive", {
    lesson: "Relics do not feed anyone. Someone still has to eat.",
    briefing: "Link three relics while the pantry stays honest. Kitchen chain is back.",
    start: { minerals: 18, food: 8, crew: 4 },
    relics: [
      { x: 0, y: 6 },
      { x: 8, y: 2 },
      { x: 8, y: 10 },
    ],
    mechanics: { kitchenChain: true },
    allowed: ["corridor", "garden", "kitchen", "weapons"],
    eatRate: 0.02,
    waves: { first: 30, interval: 26, count: 3, hp: 32, max: 1 },
    win: { relics: 3, food: 4, surviveWaves: 1 },
    par: 120,
  }),
  L("4-06", 4, "Surveyors", {
    lesson: "Four relics, two waves, a star that does not care about archaeology.",
    briefing: "The shore remembers weather. Bring a shield. Touch every monument. Hold.",
    start: { minerals: 24, food: 12, crew: 5 },
    relics: [
      { x: 0, y: 0 },
      { x: 8, y: 0 },
      { x: 0, y: 12 },
      { x: 8, y: 12 },
    ],
    deposits: [{ x: 1, y: 6 }],
    mechanics: { kitchenChain: true, flares: { first: 16, interval: 18, damage: 12, telegraph: 2.6 } },
    allowed: ["corridor", "garden", "extractor", "kitchen", "weapons", "shield", "quarters"],
    waves: { first: 22, interval: 24, count: (n) => 2 + n, hp: (n) => 28 + n * 10, max: 2 },
    eatRate: 0.018,
    win: { relics: 4, surviveWaves: 2 },
    par: 140,
  }),

  L("5-01", 5, "Shortcut", {
    lesson: "Two gates are one step.",
    briefing: "Place a pair of gates. A kapsel should cross the station without walking the long way.",
    hint: "Gates pair automatically. Staff nothing; the floor itself folds.",
    start: { minerals: 12, food: 6, crew: 3 },
    mechanics: { wormholes: true },
    allowed: ["corridor", "gate"],
    win: { rooms: { gate: 2 } },
    par: 45,
  }),
  L("5-02", 5, "Island Core", {
    lesson: "Some rooms will never touch. Fold is the only road.",
    briefing: "A garden island sits behind void. Gate to it, grow four meals.",
    start: { minerals: 16, food: 2, crew: 3 },
    blocked: [
      { x: 0, y: 9 },
      { x: 1, y: 9 },
      { x: 2, y: 9 },
      { x: 3, y: 9 },
      { x: 4, y: 9 },
      { x: 5, y: 9 },
      { x: 6, y: 9 },
      { x: 7, y: 9 },
      { x: 8, y: 9 },
    ],
    prebuilt: [{ type: "garden", x: 4, y: 11, rot: 0, built: true }],
    mechanics: { wormholes: true },
    allowed: ["corridor", "gate"],
    win: { food: 4 },
    par: 70,
  }),
  L("5-03", 5, "Ambush Fold", {
    lesson: "You can fold guns to a rim you never walked.",
    briefing: "Hold two waves. A gate-pair next to a weapon is a cheap turret truck.",
    start: { minerals: 18, food: 8, crew: 4 },
    mechanics: { wormholes: true },
    allowed: ["corridor", "gate", "weapons", "garden"],
    waves: { first: 20, interval: 24, count: (n) => 2 + n, hp: (n) => 30 + n * 10, max: 2 },
    win: { rooms: { gate: 2, weapons: 1 }, surviveWaves: 2 },
    par: 90,
  }),
  L("5-04", 5, "Three Nodes", {
    lesson: "Any built gate talks to every other built gate.",
    briefing: "Three islands. Link them. Bank minerals from the far deposit.",
    start: { minerals: 16, food: 8, crew: 4 },
    blocked: [
      { x: 3, y: 0 }, { x: 3, y: 1 }, { x: 3, y: 2 }, { x: 3, y: 3 }, { x: 3, y: 4 },
      { x: 5, y: 8 }, { x: 5, y: 9 }, { x: 5, y: 10 }, { x: 5, y: 11 }, { x: 5, y: 12 },
    ],
    deposits: [{ x: 8, y: 11 }],
    mechanics: { wormholes: true },
    allowed: ["corridor", "gate", "extractor"],
    win: { rooms: { gate: 3 }, mineral: 8 },
    par: 100,
  }),
  L("5-05", 5, "Fragile Bridge", {
    lesson: "A corridor spine is honest. A fold is fast and brittle.",
    briefing: "Relics on two islands. Link them however you like. Then hold a wave.",
    start: { minerals: 16, food: 8, crew: 4 },
    blocked: [
      { x: 4, y: 3 }, { x: 4, y: 4 }, { x: 4, y: 8 }, { x: 4, y: 9 },
    ],
    relics: [{ x: 0, y: 0 }, { x: 8, y: 12 }],
    mechanics: { wormholes: true },
    allowed: ["corridor", "gate", "weapons"],
    waves: { first: 26, interval: 24, count: 4, hp: 36, max: 1 },
    win: { relics: 2, surviveWaves: 1 },
    par: 95,
  }),
  L("5-06", 5, "Folded War", {
    lesson: "Weather, fold, and war on one small board.",
    briefing: "Two waves, flares, gates legal. Compact stations still win.",
    start: { minerals: 28, food: 14, crew: 5 },
    deposits: [{ x: 0, y: 11 }],
    mechanics: {
      wormholes: true,
      kitchenChain: true,
      flares: { first: 18, interval: 18, damage: 11, telegraph: 2.6 },
      pieceQueue: true,
    },
    allowed: ["corridor", "gate", "garden", "kitchen", "extractor", "weapons", "shield", "quarters"],
    waves: { first: 26, interval: 24, count: (n) => 1 + n, hp: (n) => 28 + n * 10, max: 2 },
    eatRate: 0.018,
    win: { surviveWaves: 2, rooms: { gate: 2 } },
    par: 130,
  }),

  L("6-01", 6, "Frost", {
    lesson: "Ice is floor you already own, only slower.",
    briefing: "The northern arm is frozen. Cross it anyway and lay two corridors beyond.",
    start: { minerals: 10, food: 6, crew: 3 },
    ice: [
      { x: 4, y: 5 },
      { x: 4, y: 4 },
      { x: 4, y: 3 },
    ],
    allowed: ["corridor"],
    win: { corridors: 2 },
    par: 50,
  }),
  L("6-02", 6, "Thaw", {
    lesson: "A staffed heater writes water back into the tile.",
    briefing: "Clear the frost. Tap the heater; kapsels standing in it radiate.",
    hint: "The heater does nothing empty.",
    start: { minerals: 10, food: 6, crew: 3 },
    ice: [
      { x: 3, y: 6 },
      { x: 5, y: 6 },
      { x: 4, y: 5 },
      { x: 4, y: 7 },
      { x: 2, y: 6 },
      { x: 6, y: 6 },
    ],
    allowed: ["corridor", "heater"],
    win: { thaw: true, rooms: { heater: 1 } },
    par: 55,
  }),
  L("6-03", 6, "Slow Patrol", {
    lesson: "A gun on ice still shoots. The kapsel just arrives late.",
    briefing: "Hold one wave. Pre-assign the weapon; frost will delay anyone you send after the alarm.",
    start: { minerals: 14, food: 8, crew: 4 },
    ice: [
      { x: 5, y: 6 },
      { x: 6, y: 6 },
      { x: 7, y: 6 },
      { x: 4, y: 4 },
      { x: 4, y: 3 },
    ],
    allowed: ["corridor", "weapons", "heater", "garden"],
    waves: { first: 16, interval: 30, count: 3, hp: 32, speed: 26, max: 1 },
    win: { rooms: { weapons: 1 }, surviveWaves: 1 },
    par: 70,
  }),
  L("6-04", 6, "Frozen Garden", {
    lesson: "You can grow on ice. You will hate the commute.",
    briefing: "Four meals. Thaw or endure. Kitchen chain is on.",
    start: { minerals: 16, food: 4, crew: 4 },
    ice: [
      { x: 3, y: 8 },
      { x: 4, y: 8 },
      { x: 5, y: 8 },
      { x: 4, y: 9 },
      { x: 4, y: 7 },
    ],
    mechanics: { kitchenChain: true },
    allowed: ["corridor", "garden", "kitchen", "heater"],
    eatRate: 0.016,
    win: { food: 6, thaw: true },
    par: 90,
  }),
  L("6-05", 6, "Black Ice", {
    lesson: "Flares do not thaw ice. They just hurt you while you slip.",
    briefing: "Thaw the belt, shield the pantry, hold a wave.",
    start: { minerals: 20, food: 10, crew: 4 },
    ice: [
      { x: 1, y: 6 },
      { x: 2, y: 6 },
      { x: 6, y: 6 },
      { x: 7, y: 6 },
      { x: 4, y: 2 },
      { x: 4, y: 1 },
    ],
    mechanics: { flares: { first: 14, interval: 16, damage: 12, telegraph: 2.5 } },
    allowed: ["corridor", "heater", "shield", "weapons", "garden"],
    waves: { first: 22, interval: 24, count: 3, hp: 34, max: 1 },
    win: { thaw: true, surviveWaves: 1, rooms: { shield: 1 } },
    par: 100,
  }),
  L("6-06", 6, "Icebreaker", {
    lesson: "The belt wants you slow when the scouts want you fast.",
    briefing: "Two waves, frost on the rim, a fold is legal if you earned it in world five. Use a heater.",
    start: { minerals: 28, food: 12, crew: 5 },
    ice: [
      { x: 0, y: 6 }, { x: 1, y: 6 }, { x: 7, y: 6 }, { x: 8, y: 6 },
      { x: 4, y: 1 }, { x: 4, y: 2 }, { x: 4, y: 10 }, { x: 4, y: 11 },
    ],
    deposits: [{ x: 0, y: 11 }],
    mechanics: { wormholes: true, kitchenChain: true, pieceQueue: true },
    allowed: ["corridor", "heater", "gate", "garden", "kitchen", "extractor", "weapons", "quarters"],
    waves: { first: 26, interval: 24, count: (n) => 1 + n, hp: (n) => 28 + n * 10, max: 2 },
    eatRate: 0.018,
    win: { surviveWaves: 2, thaw: true },
    par: 130,
  }),

  L("7-01", 7, "Unseen", {
    lesson: "Cloaked scouts are invisible until a scanner sings, or until they bite.",
    briefing: "Build and staff a scanner before the quiet gets teeth. Then hold the wave.",
    hint: "Weapons will not lead a target they cannot see.",
    start: { minerals: 16, food: 8, crew: 4 },
    mechanics: { cloak: true, cloakAll: true },
    allowed: ["corridor", "scanner", "weapons"],
    waves: { first: 16, interval: 24, count: 3, hp: 28, speed: 24, max: 1, cloaked: true },
    win: { rooms: { scanner: 1, weapons: 1 }, surviveWaves: 1 },
    par: 70,
  }),
  L("7-02", 7, "Well Trap", {
    lesson: "Gravity pulls scouts into a kill lane — and will not ask your permission.",
    briefing: "A well sits east. Place guns where the current bunches bodies.",
    start: { minerals: 16, food: 8, crew: 4 },
    wells: [{ x: 7, y: 6, strength: 70 }],
    allowed: ["corridor", "weapons", "garden"],
    waves: { first: 14, interval: 22, count: 4, hp: 30, speed: 20, max: 1 },
    win: { surviveWaves: 1, kills: 3 },
    par: 70,
  }),
  L("7-03", 7, "Overclock", {
    lesson: "Double-tap overload on a staffed extractor. It screams, then it injures itself.",
    briefing: "Bank twelve minerals. You may burn the vein to do it. Do not burn it to death.",
    hint: "Select Overload, then tap a staffed extractor or garden.",
    start: { minerals: 8, food: 8, crew: 3 },
    deposits: [{ x: 1, y: 6 }],
    mechanics: { overload: true },
    allowed: ["corridor", "extractor"],
    win: { mineral: 12 },
    par: 60,
  }),
  L("7-04", 7, "Eclipse", {
    lesson: "Cloak plus flare. See, cover, shoot.",
    briefing: "Scanner, shield, gun. One wave in bad light.",
    start: { minerals: 22, food: 10, crew: 5 },
    mechanics: {
      cloak: true,
      cloakAll: true,
      flares: { first: 12, interval: 14, damage: 12, telegraph: 2.4 },
    },
    allowed: ["corridor", "scanner", "shield", "weapons", "garden"],
    waves: { first: 18, interval: 22, count: 4, hp: 32, max: 1, cloaked: true },
    win: { surviveWaves: 1, rooms: { scanner: 1, shield: 1 } },
    par: 90,
  }),
  L("7-05", 7, "All Hands", {
    lesson: "Every toy on one board. Spend attention, not tiles.",
    briefing: "Well, frost, fold, cloak. Two waves. Leave with the pantry still yellow.",
    start: { minerals: 28, food: 14, crew: 5 },
    deposits: [{ x: 0, y: 1 }],
    ice: [{ x: 4, y: 4 }, { x: 4, y: 3 }, { x: 5, y: 6 }],
    wells: [{ x: 2, y: 10, strength: 55 }],
    mechanics: { cloak: true, cloakAll: true, wormholes: true, kitchenChain: true, overload: true, pieceQueue: true },
    allowed: ["corridor", "garden", "kitchen", "extractor", "weapons", "quarters", "gate", "heater", "scanner", "shield"],
    waves: { first: 26, interval: 24, count: (n) => 2 + n, hp: (n) => 28 + n * 10, max: 2, cloaked: true },
    eatRate: 0.016,
    win: { surviveWaves: 2, food: 4 },
    par: 140,
  }),
  L("7-06", 7, "Last Geometry", {
    lesson: "Quiet geometry. No extra advice.",
    briefing: "Four waves. Relics sit one I off the plus. Scanner before the unseen, shield before the star. Finish the survey.",
    start: { minerals: 36, food: 18, crew: 6 },
    relics: [
      { x: 2, y: 3 },
      { x: 6, y: 3 },
      { x: 2, y: 9 },
      { x: 6, y: 9 },
    ],
    deposits: [{ x: 1, y: 6 }, { x: 7, y: 6 }],
    ice: [
      { x: 4, y: 2 },
      { x: 4, y: 10 },
    ],
    wells: [{ x: 4, y: 0, strength: 48 }],
    mechanics: {
      cloak: true,
      cloakAll: true,
      wormholes: true,
      kitchenChain: true,
      overload: true,
      flares: { first: 28, interval: 20, damage: 9, telegraph: 2.8 },
      pieceQueue: true,
    },
    allowed: [
      "corridor",
      "garden",
      "kitchen",
      "extractor",
      "weapons",
      "quarters",
      "shield",
      "gate",
      "heater",
      "scanner",
      "beacon",
    ],
    waves: { first: 40, interval: 24, count: (n) => Math.min(4, 1 + n), hp: (n) => 24 + n * 7, speed: 20, max: 4, cloaked: true },
    eatRate: 0.016,
    win: { relics: 4, surviveWaves: 4 },
    par: 200,
  }),
];

export function levelById(id) {
  return LEVELS.find((l) => l.id === id);
}

export function levelsInWorld(world) {
  return LEVELS.filter((l) => l.world === world);
}

export function nextLevel(id) {
  const i = LEVELS.findIndex((l) => l.id === id);
  return i >= 0 ? LEVELS[i + 1] || null : null;
}
